/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;
import CapaDTO.CategoriaProducto;
import  CapaDTO.Producto;
import CapaNegocio.NegocioCategoriaProducto;
import CapaNegocio.NegocioProducto;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cesar
 */
public class VistaModificarProductos extends javax.swing.JFrame {

    /**
     * Creates new form VistaModificarProductos
     */
    public VistaModificarProductos() {
        initComponents();
        VistaLogin auxVista2 = new VistaLogin();
        lbl_usuario.setText(auxVista2.rut_usu);
        cargarComboBoxCategorias();
        this.setLocationRelativeTo(null);
        desHabilitar();
        VistaBodeguero auxVista = new VistaBodeguero();
        txt_idpro.setText(String.valueOf(auxVista.id_prod));
        buscarIDproducto();
    
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bto_cerrar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_precioProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_stock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_idpro = new javax.swing.JTextField();
        bto_Modificar = new javax.swing.JButton();
        bto_Salir = new javax.swing.JButton();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        txt_marca = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descrip = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_comentario = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("Rut Usuario/a:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("19635672-9");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bto_cerrar1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bto_cerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        bto_cerrar1.setText("Volver");
        bto_cerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_cerrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_usuario)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bto_cerrar1)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuario)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bto_cerrar1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txt_precioProd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_precioProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Precio Unitario :");
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Stock :");
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));

        txt_stock.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_stock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stockKeyTyped(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Categoria del Producto");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Marca :");
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Modelo :");
        jLabel10.setBorder(new javax.swing.border.MatteBorder(null));

        txt_modelo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_modelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Modificar Producto");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Descripcion");
        jLabel11.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Codigo del Producto");
        jLabel12.setBorder(new javax.swing.border.MatteBorder(null));

        txt_idpro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_idpro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_idpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idproActionPerformed(evt);
            }
        });
        txt_idpro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idproKeyTyped(evt);
            }
        });

        bto_Modificar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bto_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        bto_Modificar.setText("Modificar");
        bto_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_ModificarActionPerformed(evt);
            }
        });

        bto_Salir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bto_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        bto_Salir.setText("Salir");
        bto_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_SalirActionPerformed(evt);
            }
        });

        jComboBoxCategoria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_marca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_marca.setText(" ");
        txt_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_marcaActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Comentario");
        jLabel13.setBorder(new javax.swing.border.MatteBorder(null));

        txt_descrip.setColumns(20);
        txt_descrip.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_descrip.setRows(5);
        jScrollPane1.setViewportView(txt_descrip);

        txt_comentario.setColumns(20);
        txt_comentario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_comentario.setRows(5);
        jScrollPane2.setViewportView(txt_comentario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(bto_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_marca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_stock)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_modelo)
                                    .addComponent(txt_precioProd))
                                .addGap(1, 1, 1))
                            .addComponent(txt_idpro)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(bto_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(77, 77, 77))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idpro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(bto_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_precioProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(bto_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_marcaActionPerformed

    private void bto_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bto_SalirActionPerformed

    private void bto_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_ModificarActionPerformed
        // TODO add your handling code here:
        ModificarProducto();
        //        ValidarIngresoProducto();
    }//GEN-LAST:event_bto_ModificarActionPerformed

    private void txt_idproKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idproKeyTyped
        // TODO add your handling code here:
        if(txt_idpro.getText().length()>10)
        {
            evt.consume();

        }
    }//GEN-LAST:event_txt_idproKeyTyped

    private void txt_idproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idproActionPerformed

    private void txt_stockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stockKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();

        if(Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();
        }

        if(txt_stock.getText().length()>9)
        {
            evt.consume();

        }
    }//GEN-LAST:event_txt_stockKeyTyped

    private void bto_cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_cerrar1ActionPerformed
        this.dispose();
        VistaBodeguero pMenu = new VistaBodeguero();
        pMenu.cargarListadoDeProductos();
    }//GEN-LAST:event_bto_cerrar1ActionPerformed

   
  
//        private void cargarComboBoxCategorias(){
//            try
//            {
//                this.jComboBoxCategoria.removeAllItems();
//                NegocioCategoriaProducto auxCategoria = new NegocioCategoriaProducto();
//                ArrayList<CategoriaProducto> categorias = auxCategoria.consultaCategoriaProducto();
//                DefaultComboBoxModel modelo = new DefaultComboBoxModel();
//                for(CategoriaProducto c: categorias)
//                {
//                    modelo.addElement(c);
//
//                }
//                this.jComboBoxCategoria.setModel(modelo);
//            }
//            catch(Exception ex)
//            {
//                JOptionPane.showMessageDialog(null, "Problemas desconocidos con la base de datos: " + ex.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
//            }
//          }

     
     public void buscarIDproducto(){
        
        if (txt_idpro.getText().length()!=0)
        {
            NegocioProducto auxNegocioProducto = new NegocioProducto();
            if(auxNegocioProducto.existeProducto(Integer.parseInt(txt_idpro.getText())))
            {
                Producto auxProducto = new Producto();
                auxProducto = auxNegocioProducto.buscaProducto(Integer.parseInt(txt_idpro.getText()));
                
                CategoriaProducto auxCategoria = new CategoriaProducto();
                NegocioCategoriaProducto auxNegocioCategoria = new NegocioCategoriaProducto();
                auxCategoria = auxNegocioCategoria.buscaCategoriaProducto(auxProducto.getId_categoria_prod());
                
             
                txt_marca.setText(auxProducto.getMarca_prod());
                txt_descrip.setText(auxProducto.getDescripcion_prod());
                txt_modelo.setText(auxProducto.getModelo_prod());
                txt_precioProd.setText(String.valueOf(auxProducto.getPrecio_unitario()));
                txt_stock.setText(String.valueOf(auxProducto.getStock_prod()));
                txt_comentario.setText(String.valueOf(auxProducto.getComentario()));
                
                txt_stock.setEnabled(false);
                txt_idpro.setEnabled(false);
                jComboBoxCategoria.setEnabled(false);
                txt_descrip.setEnabled(false);
                txt_modelo.setEnabled(false);
                txt_precioProd.setEnabled(false);
                txt_comentario.setEnabled(false);
                txt_idpro.setEditable(true);
                
                 
                
            }else{
                JOptionPane.showMessageDialog(null,"El codigo del producto no existe");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese el codigo");
        }
        
    }
     
//    private void ValidarIngresoProducto() {
//        try {
//            if (this.txt_idpro.getText().length() != 0
//                    || this.jComboBoxCategoria.getSelectedIndex() + 1 == 0
//                    || this.txt_marcaProd.getText().length() != 0
//                    || this.txt_modelo.getText().length() != 0
//                    || this.txt_precioProd.getText().length() != 0) {
//                
//                 if (this.txt_idpro.getText().length() != 0
//                    || this.jComboBoxCategoria.getSelectedIndex() + 1 == 0
//                    || this.txt_marcaProd.getText().length() != 0
//                    || this.txt_modelo.getText().length() != 0
//                    || this.txt_precioProd.getText().length() != 0){
//                     
//                 }
//                 else {
//                    JOptionPane.showMessageDialog(null, "Rellene los campos correspondientes");
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "Primero busque un Producto");
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Primero busque un Producto con su ID");
//        }
//
//    }
     
     private void ModificarProducto(){
         try
        {
            if(this.bto_Modificar.getText().equals("Modificar"))
            {
                habilitar();
                this.bto_Modificar.setText("Guardar");
                this.bto_Salir.setText("Cancelar");
            }
            else
            {
                NegocioProducto auxNegocioProducto = new NegocioProducto();
                if(this.jComboBoxCategoria.getSelectedIndex()+1 == 0 
                        || this.txt_marca.getText().length()==0 
                        || this.txt_modelo.getText().length()==0 
                        || this.txt_precioProd.getText().length()==0 
                        || this.txt_stock.getText().length()==0
                        || this.txt_descrip.getText().length()==0)
                {
                    JOptionPane.showMessageDialog(null,"Faltan datos por ingresar ");
                }
                else
                {

                      Producto auxProducto = new Producto();
                      CategoriaProducto c = (CategoriaProducto) this.jComboBoxCategoria.getSelectedItem();
                      
                      auxProducto.setId_prod(Integer.parseInt(this.txt_idpro.getText()));
                      auxProducto.setId_categoria_prod(c.getId_categoria_prod());
                      auxProducto.setMarca_prod(this.txt_marca.getText());                     
                      auxProducto.setModelo_prod(this.txt_modelo.getText());                      
                      auxProducto.setDescripcion_prod(this.txt_descrip.getText());
                      auxProducto.setPrecio_unitario(Integer.parseInt(this.txt_precioProd.getText()));
                      auxProducto.setStock_prod(Integer.parseInt(this.txt_stock.getText()));
                      auxProducto.setComentario(this.txt_comentario.getText());
                      
                      auxNegocioProducto.actualizarProducto(auxProducto);
                      JOptionPane.showMessageDialog(null,"Datos guardados ");
                      limpiarFormularioDeProducto();
                
                   
                   }
                }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Datos no guardados");
        }
     }
     
     
     
     
     
        private void cerrarVentanaoCancelar(){
        try 
        {
            if (this.bto_Salir.getText().equals("Cancelar")) 
            {
                this.dispose();
                System.gc();
            } 
            else 
            {    
                this.limpiarFormularioDeProducto();
                this.bto_Salir.setText("Salir");
                this.bto_Modificar.setText("Modificar");
               
            }
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(null,"Error al Cancelar o salir de la ventana ");
        }
        }
        
    private void limpiarFormularioDeProducto()
    {
      
      
        this.jComboBoxCategoria.setSelectedIndex(-1);
        txt_idpro.setText("");
        txt_descrip.setText("");
        txt_marca.setText("");
        txt_modelo.setText("");
        txt_precioProd.setText("");
        txt_stock.setText("");
        txt_comentario.setText("");
        bto_Modificar.setText("Modificar");
        
    }
         
         
        private void cargarComboBoxCategorias(){
        try
        {
            this.jComboBoxCategoria.removeAllItems();
            NegocioCategoriaProducto auxCategoria = new NegocioCategoriaProducto();
            ArrayList<CategoriaProducto> categorias = auxCategoria.consultaCategoriaProducto();
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            for(CategoriaProducto c: categorias)
            {
                modelo.addElement(c);
            
            }
            this.jComboBoxCategoria.setModel(modelo);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Problemas desconocidos con la base de datos: " + ex.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
      }
        
    private void habilitar() {
        this.txt_marca.setEnabled(true);
        this.txt_modelo.setEnabled(true);
        this.txt_precioProd.setEnabled(true);
        this.txt_stock.setEnabled(true);
        this.txt_descrip.setEnabled(true);
        this.jComboBoxCategoria.setEnabled(true);
        this.txt_comentario.setEnabled(true);
    }

    private void desHabilitar() {
        this.txt_marca.setEnabled(false);
        this.txt_modelo.setEnabled(false);
        this.txt_precioProd.setEnabled(false);
        this.txt_stock.setEnabled(false);
        this.txt_descrip.setEnabled(false);
        this.jComboBoxCategoria.setEnabled(false);
        this.txt_comentario.setEnabled(false);

    }
     
  
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_Modificar;
    private javax.swing.JButton bto_Salir;
    private javax.swing.JButton bto_cerrar1;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTextArea txt_comentario;
    private javax.swing.JTextArea txt_descrip;
    private javax.swing.JTextField txt_idpro;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_precioProd;
    private javax.swing.JTextField txt_stock;
    // End of variables declaration//GEN-END:variables
}
