/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

import CapaDTO.CategoriaProducto;
import CapaDTO.Producto;
import CapaNegocio.NegocioCategoriaProducto;
import CapaNegocio.NegocioProducto;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cesar
 */
public class VistaCategorias extends javax.swing.JFrame {

    /**
     * Creates new form VistaCategorias
     */
    public VistaCategorias() {
        initComponents();
        VistaLogin auxVista = new VistaLogin();
        lbl_rut.setText(auxVista.rut_usu);
        cargarListadoCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_rut = new javax.swing.JLabel();
        bto_cerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_codCate = new javax.swing.JTextField();
        bto_agregarCat = new javax.swing.JButton();
        bto_eliminarCat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_categoria = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        bto_buscar = new javax.swing.JButton();
        bto_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 100));

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("Rut Usuario/a:");

        lbl_rut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_rut.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rut.setText("16258754-3");
        lbl_rut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_rut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bto_cerrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bto_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        bto_cerrar.setText("Volver");
        bto_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_cerrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Categorias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(488, 488, 488)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bto_cerrar)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rut)
                    .addComponent(bto_cerrar)
                    .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 980));

        txt_codCate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_codCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codCateActionPerformed(evt);
            }
        });

        bto_agregarCat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bto_agregarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        bto_agregarCat.setText("Agregar Categorias");
        bto_agregarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_agregarCatActionPerformed(evt);
            }
        });

        bto_eliminarCat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bto_eliminarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        bto_eliminarCat.setText("Eliminar Categorias");
        bto_eliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_eliminarCatActionPerformed(evt);
            }
        });

        table_categoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        table_categoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Categoria", "Nombre Categoria"
            }
        ));
        jScrollPane1.setViewportView(table_categoria);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Codigo Categoria");

        bto_buscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bto_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        bto_buscar.setText("Buscar");
        bto_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_buscarActionPerformed(evt);
            }
        });

        bto_actualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bto_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        bto_actualizar.setText("Actualizar");
        bto_actualizar.setToolTipText("");
        bto_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_codCate, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(bto_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bto_actualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(249, 249, 249)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bto_agregarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bto_eliminarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_codCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bto_buscar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bto_actualizar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(bto_agregarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(bto_eliminarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bto_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_cerrarActionPerformed
        // TODO add your handling code here:
        VistaLogin login = new VistaLogin();
        login.redireccionarVentana(lbl_rut.getText());
        this.dispose();
    }//GEN-LAST:event_bto_cerrarActionPerformed

    private void bto_agregarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_agregarCatActionPerformed
         VistaAgregarCategoria cate = new VistaAgregarCategoria();
        cate.setVisible(true);
        
    }//GEN-LAST:event_bto_agregarCatActionPerformed

    private void bto_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_buscarActionPerformed
          buscarCategoriaID(txt_codCate.getText());
    }//GEN-LAST:event_bto_buscarActionPerformed

    private void bto_eliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_eliminarCatActionPerformed
        // TODO add your handling code here:
        eliminarCategoria();
    }//GEN-LAST:event_bto_eliminarCatActionPerformed

    private void txt_codCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codCateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codCateActionPerformed

    private void bto_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_actualizarActionPerformed
        // TODO add your handling code here:
        cargarListadoCategoria();
    }//GEN-LAST:event_bto_actualizarActionPerformed
public void buscarCategoriaID(String id_cate)
    {
        try
        {
            if(txt_codCate.getText().length()!=0)
            {
                NegocioCategoriaProducto auxNegocioCategoriaProducto = new NegocioCategoriaProducto();
                if(auxNegocioCategoriaProducto.existeCategoria(Integer.parseInt(id_cate)))
                {
                    
                
                DefaultTableModel modelo = new DefaultTableModel();
                modelo = (DefaultTableModel) this.table_categoria.getModel();
                modelo.setNumRows(0);
                
         
                CategoriaProducto auxCategoria= new CategoriaProducto();
            

                auxCategoria = auxNegocioCategoriaProducto.buscaCategoriaProducto(Integer.parseInt(id_cate));
                int fila = 0;
                int monto_final =0;
                
                Producto auxProduc = new Producto();
                Object[] num = {};
                modelo.addRow(num);
                this.table_categoria.setValueAt(auxCategoria.getId_categoria_prod() , fila, 0);
                this.table_categoria.setValueAt(auxCategoria.getNombre_categoria(), fila, 1);   
                    
                }else{
                    JOptionPane.showMessageDialog(null, "El Id ingresado no existe");
                }
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Ingrese primero el id de unacategoria");
                cargarListadoCategoria();
            }
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"No se ha podido listar a las ventas ");
        }
    }

 private void eliminarCategoria(){
        try
        {
            int cantidad_usuarios = this.table_categoria.getModel().getRowCount();
            if(cantidad_usuarios > 0)
            {
                int fila_seleccionada = this.table_categoria.getSelectedRow();
                if(fila_seleccionada > -1)
                {
                    int respuesta = JOptionPane.showConfirmDialog(null,"Estas seguro de continuar con el proceso de eliminacion?.\nEste proceso no se puede deshacer.", "Mensaje", JOptionPane.YES_NO_OPTION,  JOptionPane.QUESTION_MESSAGE);
                    if(respuesta == JOptionPane.YES_OPTION)
                    {
                        String id = this.table_categoria.getModel().getValueAt(fila_seleccionada, 0).toString();
                        NegocioCategoriaProducto auxNegocio = new NegocioCategoriaProducto();
                        auxNegocio.eliminarCategoriaProducto(Integer.parseInt(id));
                        
                        JOptionPane.showMessageDialog(null, "Producto eliminado satisfactoriamente.", "Mensajes", JOptionPane.INFORMATION_MESSAGE);
                        cargarListadoCategoria();
                    }
                }
                
            }
            
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Problemas desconocidos con la base de datos: " + ex.getMessage(), "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }
 
 public void cargarListadoCategoria(){
        try
        {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo = (DefaultTableModel) this.table_categoria.getModel();
        
            modelo.setNumRows(0);
        
            int fila = 0;
        
     
            NegocioCategoriaProducto auxNegocioCategoria = new NegocioCategoriaProducto();
            
        
            Iterator iter = auxNegocioCategoria.consultaCategoriaProducto().iterator();
        
            while(iter.hasNext())
            {
                CategoriaProducto auxCategoria = new CategoriaProducto();
                auxCategoria = (CategoriaProducto) iter.next();
                Object[] num = {};
                modelo.addRow(num);
                auxCategoria = auxNegocioCategoria.buscaCategoriaProducto(auxCategoria.getId_categoria_prod());
                this.table_categoria.setValueAt(auxCategoria.getId_categoria_prod(), fila, 0);
                this.table_categoria.setValueAt(auxCategoria.getNombre_categoria(), fila, 1);
       
                fila++;
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"No se han podido listar los Productos " + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_actualizar;
    private javax.swing.JButton bto_agregarCat;
    private javax.swing.JButton bto_buscar;
    private javax.swing.JButton bto_cerrar;
    private javax.swing.JButton bto_eliminarCat;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_rut;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable table_categoria;
    private javax.swing.JTextField txt_codCate;
    // End of variables declaration//GEN-END:variables
}
