/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

import CapaDTO.Usuario;
import CapaNegocio.NegocioUsuario;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar
 */
public class VistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VistaLogin
     */
    public VistaLogin() {
        initComponents();
        this.jInternalFrame1.setTitle("Bienvenido");
        
    }
    
    public static String rut_usu = "";
    
    public void validarUsuario()
    {
        NegocioUsuario auxNegocioUsuario = new NegocioUsuario();
        if (txt_rut.getText().length()==0 || txt_contrasena.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
        }else{
            if(auxNegocioUsuario.existeUsuario(txt_rut.getText()))
            {
                
                Usuario auxUsuario = new Usuario();
                auxUsuario = auxNegocioUsuario.buscaUsuario(txt_rut.getText());
                if(auxUsuario.getContrasena_usu().equals(txt_contrasena.getText()) )
                {
                    redireccionarVentana(txt_rut.getText());
                    rut_usu = txt_rut.getText();
                }else
                {
                    JOptionPane.showMessageDialog(null, "Contreña incorrecta");
                }
                        
                
            }else{
                JOptionPane.showMessageDialog(null, "El rut es incorrecto");
            }
        }
    }
    
    public void redireccionarVentana(String rut_usu){
        
        
        NegocioUsuario auxNegocioUsuario = new NegocioUsuario();
        int rol = auxNegocioUsuario.consultarCargo(rut_usu);
        VistaCajero auxVista1 = new VistaCajero();
        VistaVendedor auxVista2 = new VistaVendedor();
        VistaBodeguero auxVista3 = new VistaBodeguero();
        VistaAdmin auxVista4 = new VistaAdmin();
        
        if(rol == 1)
        {
            auxVista1.setVisible(true);
            auxVista1.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        } else if(rol == 2)
        {
            auxVista2.setVisible(true);
            auxVista2.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        } else if (rol == 3)
        {
            auxVista3.setVisible(true);
            auxVista3.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        } else if(rol==4)
        {
            auxVista4.setVisible(true);
            auxVista4.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        }
        
        
    }
    
    
    public void redireccionarCerrar(String rut_usu){
        
        NegocioUsuario auxNegocioUsuario = new NegocioUsuario();
        VistaLogin auxLogin = new VistaLogin();
        int rol = auxNegocioUsuario.consultarCargo(rut_usu);
        VistaCajero auxVista1 = new VistaCajero();
        VistaVendedor auxVista2 = new VistaVendedor();
        VistaBodeguero auxVista3 = new VistaBodeguero();
        VistaAdmin auxVista4 = new VistaAdmin();
        
        if(rol == 1)
        {
            auxLogin.setVisible(true);
            auxLogin.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        } else if(rol == 2)
        {
            auxLogin.setVisible(true);
            auxLogin.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        } else if (rol == 3)
        {
            auxLogin.setVisible(true);
            auxLogin.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        } else if(rol==4)
        {
            auxVista4.setVisible(true);
            auxVista4.setExtendedState(MAXIMIZED_BOTH);
            this.dispose();
        }
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();
        bto_ingresar = new javax.swing.JButton();
        txt_contrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jInternalFrame1.setVisible(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Rut:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Contraseña:");

        txt_rut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_rut.setToolTipText("");
        txt_rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rutKeyTyped(evt);
            }
        });

        bto_ingresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bto_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        bto_ingresar.setText("Ingresar");
        bto_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_ingresarActionPerformed(evt);
            }
        });

        txt_contrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contrasenaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_contrasena)
                            .addComponent(txt_rut, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(bto_ingresar)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_rut)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bto_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel1.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 430, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bto_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_ingresarActionPerformed
        // TODO add your handling code here:
        rut_usu = txt_rut.getText();
        validarUsuario();
        
    }//GEN-LAST:event_bto_ingresarActionPerformed

    private void txt_rutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rutKeyTyped
        // TODO add your handling code here:
        if(txt_rut.getText().length()>9)
        {
            evt.consume();
            
        }
    }//GEN-LAST:event_txt_rutKeyTyped

    private void txt_contrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contrasenaKeyTyped
        // TODO add your handling code here:
        if(txt_contrasena.getText().length()>49)
        {
            evt.consume();
            
        }
    }//GEN-LAST:event_txt_contrasenaKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto_ingresar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_contrasena;
    private javax.swing.JTextField txt_rut;
    // End of variables declaration//GEN-END:variables
}
